# 1 矩阵

# （M行, N列）* （N行,L列）=（M行,L列）

In [1]:
# 和array的区别矩阵必须是二维的，但是array可以是多维的
# 如 3*2 矩阵，即 3行2列，如m为行，n为列，那么m*n即3*2
# 矩阵的维数即行数*列数

# 2 向量

In [2]:
# 向量是一种特殊的矩阵，讲义中的向量一般都是列向量，
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr+1

array([2, 3, 4, 5])

In [6]:
arr/2

array([0.5, 1. , 1.5, 2. ])

In [7]:
arr*10

array([10, 20, 30, 40])

In [14]:
arr1=np.array([[1,2,3,2,1,4],[5,6,1,2,3,1]])
arr2=np.array([[1,2,3,4,5,7],[3,4,5,6,7,2]])

In [15]:
arr1+arr2

array([[ 2,  4,  6,  6,  6, 11],
       [ 8, 10,  6,  8, 10,  3]])