# Numpy（科学计算）
##   数据结构ndarray（多维数组）
##   ndarray的相关操作
#   ndarray进阶知识

# 

# Scipy
#   向量
#   矩阵
#   特征值和特征向量
#   解线性方程组
#   最小二乘

In [1]:
# Python基本类型
# 数字类型
#  整型
#     布尔型(bool)、整型(int)、长整型(long)
#  非整型
#     浮点(float)、复数(complex)

# 容器
#  序列
#     字符串(str)、列表(list)、元组(tuple)
#  集合
#     可变集合(set)、不可变集合(frozenset)
#  映射
#     字典(dict)

## 高效的固定类型数组
## Numpy提供了一种高效存储固定类型的数组: ndarray
## 数据存储在专门的字段中
## 所有字段共享类型等信息

In [2]:
# ndarray
# 只能存储同一种类型的数据，不能动态增加长度，计算性能好，存储冗余少

# list
# 支持同时存储不同类型的数据，可以动态增加长度，计算性能一般，存储冗余多

# Numpy的基本作法

In [2]:
import numpy as np #导入模块，并命名为np

In [12]:
# 从list创建一个ndarray数组

x = np.array([[1,2,3],[4,5,6]]) # 创建一个ndarray数组
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 查看类型

type(x)

numpy.ndarray

In [14]:
# 维度数

x.ndim

2

In [15]:
# 数组形状（每一维的大小）

x.shape

(2, 3)

In [16]:
# 数组中元素总数

x.size

6

In [17]:
# 数组中元素的数据类型

x.dtype

dtype('int64')

In [18]:
# 数组中每个元素所需的内存空间（单位：字节）

x.itemsize

8

In [19]:
# 内存中从一个元素移动到下一个元素所需的偏移量（单位：字节）
# 24表示，沿着第一个维度移动到下一个元素要偏移24个字节
# 8表示，沿着第二个维度移动到下一个元素老板娘偏移8个字节

x.strides

(24, 8)

In [21]:
# 存储该数组所需的总大小（字节）= x.itemsize * x.size

x.nbytes

48

In [22]:
# 数组元素对应的内存区域

x.data

In [24]:
# 通过bytearray将内存地址转换成字节串
# 通过字节串可以看到前8个字节存储的是1，依次是2，3，4，5，6
# 通过字节串可以知道，Numpy中的ndarray是按照行来存储数据

bytearray(x.data)

bytearray(b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00')

# 从list创建

In [25]:
# 一维array

x = np.array([1,2,3])
x

array([1, 2, 3])

In [26]:
# 二维array

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 三维array

x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
# 指定array元素的数据类型

x = np.array([1,2,3],dtype=float)
x

array([1., 2., 3.])

In [33]:
# 自动向高精度转换

x = np.array([1,2,3.0])
x

array([1., 2., 3.])

In [31]:
# C语言风格

x = np.array([[1,2,3],[4,5,6]], order='c')
print(x)
print(x.itemsize)
print(x.strides)

[[1 2 3]
 [4 5 6]]
8
(24, 8)


In [35]:
# Fortran语言风格

x = np.array([[1,2,3],[4,5,6]], order='F')
print(x)
print(x.itemsize)
print(x.strides)

[[1 2 3]
 [4 5 6]]
8
(8, 16)


# 创建一个初始化的array

In [39]:
# 全0数组

x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
# 根据一个数组的shape和type创建一个全0数组

a = np.array([1,2,3])
b = np.zeros_like(a)
print(b)

[0 0 0]


In [41]:
# 全1数组

x = np.ones([2,3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# 根据一个数组的shape和type创建一个全1数组

a = np.array([1,2,3])
b = np.ones_like(a)
b

array([1, 1, 1])

In [43]:
# 全指定值的数组

x = np.full([2,3],3, dtype=float)
x

array([[3., 3., 3.],
       [3., 3., 3.]])

In [46]:
# 根据一个数组的shape和type创建一个全指定值的数组

a = np.array([1,2,3])
b = np.full_like(a,4)
b

array([4, 4, 4])

In [51]:
# 二维对角数组
# np.eye(N,M,k)
# N: 行数
# M: 列数
# k: 0表示中间一条对角线，正数表示向上移k条对角线，负数表示向下
a = np.eye(3,3,0)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
b = np.eye(3,3,1)
b

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [64]:
c = np.eye(5,3,-2)
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 创建一个等分区间的array

## 根据固定步长等分区间: arange
### np.arange([start,] stop[, step,], dtype=None)
### start: 起点
### stop: 终点
### step: 每次增加的步长

### 返回: 从start开始，每隔step取一个值，直到超过stop

In [65]:
# 根据固定步长等分区间
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 根据分隔点数分割区间: linspace
### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
### start: 起点
### stop: 终点
### num: 返回多少个点
### endpoint: 终点是否包含在内
### • True = 把区间[start, stop]等分成num-1份，加上终点得num个点
### • False = 把区间[start, stop]等分成num份，不包含终点得num个点
### retstep: 结果是否返回步长，如果为True，则返回值为有两个元素的tuple，第一个是数组，第二个是步长
### dtype: 数据类型

In [66]:
# 根据分隔点数分割区间
x = np.linspace(0,5,5)
x

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [67]:
# 不包含终点
x = np.linspace(0, 5, 5, endpoint=False)
x

array([0., 1., 2., 3., 4.])

In [68]:
# 以上等价于
x = np.linspace(0,5,6)[:-1]
x

array([0., 1., 2., 3., 4.])

In [72]:
# 返回步长
x, step = np.linspace(0, 5, 5, retstep=True)
print(x)
print(step)

[0.   1.25 2.5  3.75 5.  ]
1.25


# 从函数创建array
### np.fromfunction(function, shape, **kwargs)
### function: 定义一个函数，接受N个参数（N=维数），这N个参数表示数组中一个元素的下标，根据下标计算一个返回值
### shape: 定义数组每个维度的大小
### dtype: 定义function所接受参数的类型

In [73]:
# 位置(i, j)的元素等于 i+j
x = np.fromfunction(lambda x, y: x + y, (3,4))
print(x)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


In [74]:
# 位置(i,j)的元素等于 i+j, 通过dtype来控制参数的类型
x = np.fromfunction(lambda x, y: x+y, (3, 4), dtype=int)
print(x)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [76]:
# x + y 为奇数的位置(i, y)取1, 其余为0
x = np.fromfunction(lambda x, y:(x+y) % 2, (3,4),dtype=int)
print(x)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


# 隐式类型转换
### 在创建array的时候通过dtype指定数据类型

In [5]:
v1 = np.array([True, False])
print(v1,type(v1))

[ True False] <class 'numpy.ndarray'>


In [7]:
# bool_ -> int8
v1 = np.array([True, False], dtype=np.int8)
v1

array([1, 0], dtype=int8)

In [8]:
# bool_ -> float16
np.array([True, False], dtype=np.float16)

array([1., 0.], dtype=float16)

In [9]:
# int_ -> float32
np.array([1,2,3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [10]:
# float_ -> int8
np.array([1.23, 2.34, 3.45], dtype=np.int8)

array([1, 2, 3], dtype=int8)

# 显示类型转换
### 直接使用需要的类型转换

In [11]:
# 直接使用需要的类型转换
x = np.array([1.2, 2.3, 3.4])
np.int8(x)

array([1, 2, 3], dtype=int8)

### 使用ndarray.astype方法转换

In [12]:
# 使用astype()方法转换
x = np.array([1.2, 2.3, 3.4])
x.astype(np.int8)

array([1, 2, 3], dtype=int8)

# 数据类型的字符表达

In [16]:
# 查看支持的所有字符表达
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'ulong': numpy.uint64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex12

In [17]:
# 指定类型为1个字节的int
x = np.array([1, 2.2, 3, 4], dtype='i1')
x

array([1, 2, 3, 4], dtype=int8)