In [1]:
pip list

Package                   Version
------------------------- --------------
anyio                     4.3.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.15.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
comm                      0.2.2
contourpy                 1.1.1
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
exceptiongroup            1.2.1
executing                 2.0.1
fastjsonschema            2.19.1
filelock                  3.9.0
fonttools                 4.51.0
fqdn                      1.5.1
fsspec                    2023.4.0
h11                       0.14.0
httpcore     

In [2]:
conda env list

# conda environments:
#
base                     /home/leon/anaconda3
bert                     /home/leon/anaconda3/envs/bert
pytorch               *  /home/leon/anaconda3/envs/pytorch
vgg16                    /home/leon/anaconda3/envs/vgg16


Note: you may need to restart the kernel to use updated packages.


# Tensors(张量)

In [3]:
from __future__ import print_function

In [63]:
import torch
import math

In [5]:
x = torch.empty(5,3)

In [6]:
x

tensor([[-8.1236e+08,  4.1429e-41, -8.1236e+08],
        [ 4.1429e-41,  3.2799e-09,  1.6897e-04],
        [ 4.2887e-08,  5.2356e+22,  1.0441e-08],
        [ 3.3352e-09,  6.6719e-10,  2.3051e-12],
        [ 2.6302e+20,  6.1949e-04,  6.4805e-10]])

In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.2536, 0.9464, 0.5057],
        [0.4637, 0.0490, 0.5848],
        [0.6099, 0.8667, 0.4342],
        [0.0282, 0.5876, 0.5662],
        [0.0521, 0.7250, 0.5266]])


In [8]:
x = torch.zeros(5,3,dtype=torch.long)

In [9]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x,dtype=torch.float)

In [13]:
print(x)

tensor([[ 1.0853,  0.5077, -0.2676],
        [ 0.3520,  0.8518, -0.2035],
        [ 0.0817,  0.8327,  2.2980],
        [-1.2299,  0.1524, -2.0011],
        [-2.1689,  0.0615, -0.1444]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [15]:
torch.Size([5,3])

torch.Size([5, 3])

In [16]:
y = torch.rand(5,3)

In [17]:
print(x+y)

tensor([[ 2.0494,  1.0752, -0.2438],
        [ 1.0741,  0.9496,  0.7230],
        [ 1.0198,  1.3615,  2.6053],
        [-0.6068,  0.8670, -1.2532],
        [-1.3984,  0.4090,  0.1517]])


In [18]:
print(torch.add(x,y))

tensor([[ 2.0494,  1.0752, -0.2438],
        [ 1.0741,  0.9496,  0.7230],
        [ 1.0198,  1.3615,  2.6053],
        [-0.6068,  0.8670, -1.2532],
        [-1.3984,  0.4090,  0.1517]])


In [20]:
result=torch.empty(5,3)
torch.add(x,y,out=result)

tensor([[ 2.0494,  1.0752, -0.2438],
        [ 1.0741,  0.9496,  0.7230],
        [ 1.0198,  1.3615,  2.6053],
        [-0.6068,  0.8670, -1.2532],
        [-1.3984,  0.4090,  0.1517]])

In [21]:
y.add_(x)
print(y)

tensor([[ 2.0494,  1.0752, -0.2438],
        [ 1.0741,  0.9496,  0.7230],
        [ 1.0198,  1.3615,  2.6053],
        [-0.6068,  0.8670, -1.2532],
        [-1.3984,  0.4090,  0.1517]])


In [22]:
print(x)

tensor([[ 1.0853,  0.5077, -0.2676],
        [ 0.3520,  0.8518, -0.2035],
        [ 0.0817,  0.8327,  2.2980],
        [-1.2299,  0.1524, -2.0011],
        [-2.1689,  0.0615, -0.1444]])


In [23]:
print(x[:,1])

tensor([0.5077, 0.8518, 0.8327, 0.1524, 0.0615])


In [24]:
print(x[0,1])

tensor(0.5077)


In [25]:
print(x[0:0,1])

tensor([])


In [26]:
print(x[:1,1])

tensor([0.5077])


In [29]:
print(x[1:,1])

tensor([0.8518, 0.8327, 0.1524, 0.0615])


In [30]:
print(x)

tensor([[ 1.0853,  0.5077, -0.2676],
        [ 0.3520,  0.8518, -0.2035],
        [ 0.0817,  0.8327,  2.2980],
        [-1.2299,  0.1524, -2.0011],
        [-2.1689,  0.0615, -0.1444]])


In [34]:
print(x[:1,2])

tensor([-0.2676])


In [35]:
print(x[1,:])

tensor([ 0.3520,  0.8518, -0.2035])


In [36]:
print(x[3,:])

tensor([-1.2299,  0.1524, -2.0011])


In [37]:
print(x[:4,1])

tensor([0.5077, 0.8518, 0.8327, 0.1524])


In [38]:
print(x[:3,1])

tensor([0.5077, 0.8518, 0.8327])


In [52]:
print(x[3,1])

tensor(0.1524)


In [53]:
x = torch.randn(4,4)

In [54]:
y = x.view(16)

In [55]:
z=x.view(-1,8)

In [56]:
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [59]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.9164])
-0.9163738489151001


In [60]:
x = torch.ones(2,2,requires_grad=True)

In [61]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [62]:
print(y.grad_fn)

None


In [68]:
z = pow(x,2)*3
out=z.mean()

In [69]:
print(z,out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


In [70]:
a=torch.randn(2,2)

In [71]:
a=((a*3)/(a-1))

In [72]:
print(a.requires_grad)

False


In [73]:
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

True


In [74]:
out.backward()
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [75]:
x = torch.randn(3,requires_grad=True)
y = x* 2

while y.data.norm() < 1000:
    y *= 2
print(y)

tensor([-1130.2938,  -519.1516, -1376.0470], grad_fn=<MulBackward0>)


In [76]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [77]:
print(x.requires_grad)
print(pow(x,2).requires_grad)

with torch.no_grad():
    print(pow(x,2).requires_grad)

True
True
False
