In [3]:
x = torch.ones(2,2,requires_grad=True)

In [4]:
import torch

In [5]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x +2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
print(y.grad_fn)

In [8]:
z = y* y *3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2,2)

In [10]:
a=((a*3)/(a-1))

In [11]:
print(a.requires_grad)

False


In [12]:
a.requires_grad_(True)

tensor([[-1.3494, -5.6346],
        [ 0.7800, -0.0455]], requires_grad=True)

In [13]:
print(a.requires_grad)

True


In [14]:
b=(a*a).sum()
print(b.grad_fn)

In [15]:
out.backward()

In [16]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
